### PR TITLE
Controller

### PR DESCRIPTION
**Pull request by matthewkos**
The (text) controller of the bot
just need to see the Javadoc commented methods
added class: 
Feature: SuperClass of Feature, subclasses need to implement method _call()_
FeatureSudo: sample dialogue
FeatureDefaultHandler: handle unknown text
User: store the information of the previous record in _String Context_ and parameters in _HashMap<String param_name,String param_value>_

### CODE REVIEW

**Comment by matthewkos** [comment]
Just view these file is enough
KitchenSinkController
User
Feature*

**Comment by FrancoTheOne** [comment]
okok... but the user will not save as objects in later work?

**Comment by matthewkos** [comment]
I have find a way to store the User objects as static and long-living. They are userID dependent, so that you can save some variables inside the User HashMap. The variable can be used for later work.

**Comment by FrancoTheOne** [comment]
but the better choice should be save everything in the database
then when an ID requested for yoyoyo, create a new temporary object at that time

**Pull request merged**
